### ISSUE TITLE
How to change TAG from AbNeR ResetScore to a Custom TAG!

### ISSUE THREAD

**Issue by psychogaming** [abnerfs/abner_resetscore#3]
it would be great option to change the tag!

**Comment by abnerfs** [comment]
You will need to change in .sp file and recompile the plugin

**Comment by psychogaming** [comment]
how can you please suggest any video to do that!

**Comment by abnerfs** [comment]
Duplication of https://github.com/abnerfs/abner_resetscore/issues/3
