### ISSUE TITLE
New CSGO Update causing issues.

### ISSUE THREAD

**Issue by RouterRage-dev** [abnerfs/abner_resetscore#4]
Hello. When you reset your score after the new update, the points don't get reset. I have included a picture of the bug below. If this could please be looked into that would be great. I know there's all other communities with the plugin are dealing with the exact same issue at the moment.

Best regards,
RouterRge

![image](https://user-images.githubusercontent.com/56137561/69485190-51b71100-0e3c-11ea-9a70-e96b5e707ec8.png)

**Comment by abnerfs** [comment]
Hi, have you tried to update your gamedata file? **addons\sourcemod\gamedata\sm-cstrike.games\game.csgo.txt**

Updated gamedata content:
https://raw.githubusercontent.com/alliedmodders/sourcemod/82df6087afa62385823fe08749b04a40f00c028a/gamedata/sm-cstrike.games/game.csgo.txt


Commit detail: https://github.com/alliedmodders/sourcemod/commit/82df6087afa62385823fe08749b04a40f00c028a#diff-8394632b696676f65c34ae9591dcfcaf
