### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by imruckingfetarded** [abnerfs/abner_resetscore#5]
I was wondering if there is anyway for it to say "[SM]" or "[Rucking] instead of "[AbNeR ResetScore]"

**Comment by abnerfs** [comment]
Yeah there is a way editing source code but I'm kinda busy right now. I'm not editing public plugins for now, just paid ones, if you're interested I can send you a price.

**Comment by abnerfs** [comment]
With the new v1.5.1 you can change it in the translations file
