### ISSUE TITLE
Resetscore plugin compile issue

### ISSUE THREAD

**Issue by DaDeMarcu** [abnerfs/abner_resetscore#9]
So i re-write the plugin with some few changes , but when i try to compile it (with a local compiler not the web one) , it says mostly that CPrintToChat and CPrintToChatALL is undefined symbol , and it doesn't let me compile it , can i get a help or something.
Thank you!!!!

**Comment by abnerfs** [comment]
You need the colors.inc file that is in the download, paste it inside your include folder it should work
